services:
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app

  python:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "5000:5000"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /app

