services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./node
        target: /app

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "5000:5000"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./python
        target: /app

