services:
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "49513:49513"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app

  python:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "49515:49515"
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /app

